### PR TITLE
chore: update and adhere to lint settings

### PR DESCRIPTION
**Pull request by chadoh**
environment/.eslintrc defined many settings, but some of these weren't
being used at all and other standards were being used in the code
(example: lint settings required semicolons, but no code used them)

this updates settings to match the code for several rules, and updates
the code to match the settings for the others

before merge:

- [ ] add lint step to CI

### CODE REVIEW

**Comment by chadoh** [comment]
before merge:

- [ ] add lint step to CI

**Comment by chadoh** [comment]
@Kouprin do we want this?

**Comment by Kouprin** [comment]
> @Kouprin do we want this?

Absolutely. I'd like to discuss about it on Bridge Meeting.

**Comment by Kouprin** [comment]
PR bankruptcy rule. We will enable linter in CI after architecture update

**Pull request closed without merging**
