### PR TITLE
Remove test flag

### PR DESCRIPTION
**Pull request by ailisp**
Fix https://github.com/near/rainbow-bridge-cli/issues/247
This has to be merge together with:
https://github.com/near/rainbow-bridge-lib/pull/5
https://github.com/near/rainbow-bridge-rs/pull/6

ci is expected to fail now, but after above two pr merged should ci must pass

### CODE REVIEW

**Comment by Kouprin** [comment]
Where do we really validate ethash?

**Comment by nearmax** [comment]
> > Where do we really validate ethash?
> 
> We always validate ethash and validate=False is not used even in tests, so i just drop it

We need this parameter for tests, because Ganache is not doing PoW, and therefore headers produced by Ganache do not have correct ethash. The same applies to PoA networks. When our e2e tests start Ganache, the start command writes this param  as false into config https://github.com/near/rainbow-bridge-cli/blob/master/commands/start/ganache.js#L31

**Review by nearmax — CHANGES_REQUESTED** [review]
> > Where do we really validate ethash?
> 
> We always validate ethash and validate=False is not used even in tests, so i just drop it

We need this parameter for tests, because Ganache is not doing PoW, and therefore headers produced by Ganache do not have correct ethash. The same applies to PoA networks. When our e2e tests start Ganache, the start command writes this param  as false into config https://github.com/near/rainbow-bridge-cli/blob/master/commands/start/ganache.js#L31

So we should add compilation flag into https://github.com/near/rainbow-bridge-rs/pull/6 and move `near-client-validate-ethash` into `prepare` command.

**Comment by Kouprin** [comment]
PR bankruptcy rule

**Pull request closed without merging**
